<?php

namespace Database\Seeders;

use App\Models\Resident;
use Illuminate\Database\Seeder;

class ResidentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Resident::create([
            'id' => '1',
            'residentID' => 'RES-00001',
            'firstName' => 'Admin',
            'middleName' => 'PCSZ',
            'lastName' => 'Capstone',
            'dateOfBirth' => '2000-01-01',
            'contactNumber' => '09876543210',
            'email' => 'adminPersonalEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Account Manager',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
            ]);
        
        // houseID 2
        Resident::create([
            'id' => '2',
            'residentID' => 'RES-00002',
            'firstName' => 'Andres',
            'middleName' => 'Jefferson',
            'lastName' => 'Morales',
            'dateOfBirth' => '1970-05-07',
            'contactNumber' => '09876543211',
            'email' => 'andres@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Firefighter',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '3',
            'residentID' => 'RES-00003',
            'firstName' => 'Rio',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '1980-03-07',
            'contactNumber' => '09876543111',
            'email' => 'rio@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '4',
            'residentID' => 'RES-00004',
            'firstName' => 'Miles',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '2000-02-07',
            'contactNumber' => '09876541111',
            'email' => 'morales@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Barangay Health Worker',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 3
        Resident::create([
            'id' => '5',
            'residentID' => 'RES-00002',
            'firstName' => 'Andres',
            'middleName' => 'Jefferson',
            'lastName' => 'Morales',
            'dateOfBirth' => '1970-05-07',
            'contactNumber' => '09876543211',
            'email' => 'andres@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Firefighter',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '6',
            'residentID' => 'RES-00003',
            'firstName' => 'Rio',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '1980-03-07',
            'contactNumber' => '09876543111',
            'email' => 'rio@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '7',
            'residentID' => 'RES-00004',
            'firstName' => 'Miles',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '2000-02-07',
            'contactNumber' => '09876541111',
            'email' => 'morales@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Barangay Health Worker',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 4
        Resident::create([
            'id' => '8',
            'residentID' => 'RES-00002',
            'firstName' => 'Andres',
            'middleName' => 'Jefferson',
            'lastName' => 'Morales',
            'dateOfBirth' => '1970-05-07',
            'contactNumber' => '09876543211',
            'email' => 'andres@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Firefighter',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '9',
            'residentID' => 'RES-00003',
            'firstName' => 'Rio',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '1980-03-07',
            'contactNumber' => '09876543111',
            'email' => 'rio@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '10',
            'residentID' => 'RES-00004',
            'firstName' => 'Miles',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '2000-02-07',
            'contactNumber' => '09876541111',
            'email' => 'morales@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Barangay Health Worker',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '11',
            'residentID' => 'RES-00017',
            'firstName' => 'Joseph',
            'middleName' => 'Jefferson',
            'lastName' => 'Morales',
            'dateOfBirth' => '2008-02-07',
            'contactNumber' => '09876533211',
            'email' => 'joseph@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Unemployed',
            'monthlyIncome' => 'None',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 5
        Resident::create([
            'id' => '12',
            'residentID' => 'RES-00005',
            'firstName' => 'Gwen',
            'middleName' => 'Maxine',
            'lastName' => 'Stacy',
            'dateOfBirth' => '2001-02-20',
            'contactNumber' => '09876543212',
            'email' => 'stacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Secretary',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '13',
            'residentID' => 'RES-00006',
            'firstName' => 'James',
            'middleName' => 'Madelyn',
            'lastName' => 'Stacy',
            'dateOfBirth' => '1997-02-20',
            'contactNumber' => '09876543212',
            'email' => 'jamestacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 6
        Resident::create([
            'id' => '14',
            'residentID' => 'RES-00005',
            'firstName' => 'Gwen',
            'middleName' => 'Maxine',
            'lastName' => 'Stacy',
            'dateOfBirth' => '2001-02-20',
            'contactNumber' => '09876543212',
            'email' => 'stacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Secretary',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '15',
            'residentID' => 'RES-00006',
            'firstName' => 'James',
            'middleName' => 'Madelyn',
            'lastName' => 'Stacy',
            'dateOfBirth' => '1997-02-20',
            'contactNumber' => '09876543212',
            'email' => 'jamestacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 7
        Resident::create([
            'id' => '16',
            'residentID' => 'RES-00005',
            'firstName' => 'Gwen',
            'middleName' => 'Maxine',
            'lastName' => 'Stacy',
            'dateOfBirth' => '2001-02-20',
            'contactNumber' => '09876543212',
            'email' => 'stacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Secretary',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '17',
            'residentID' => 'RES-00006',
            'firstName' => 'James',
            'middleName' => 'Madelyn',
            'lastName' => 'Stacy',
            'dateOfBirth' => '1997-02-20',
            'contactNumber' => '09876543212',
            'email' => 'jamestacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 8
        Resident::create([
            'id' => '18',
            'residentID' => 'RES-00007',
            'firstName' => 'Francine',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'francine@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Captain',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '19',
            'residentID' => 'RES-00008',
            'firstName' => 'Juan',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'frances@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 10
        Resident::create([
            'id' => '20',
            'residentID' => 'RES-00007',
            'firstName' => 'Francine',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'francine@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Captain',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '21',
            'residentID' => 'RES-00008',
            'firstName' => 'Juan',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'frances@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 12
        Resident::create([
            'id' => '22',
            'residentID' => 'RES-00007',
            'firstName' => 'Francine',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'francine@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Captain',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '23',
            'residentID' => 'RES-00008',
            'firstName' => 'Juan',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'frances@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '24',
            'residentID' => 'RES-00018',
            'firstName' => 'Frances',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '1960-11-11',
            'contactNumber' => '09876543211',
            'email' => 'francesca@gmail.com',
            'maritalStatus' => 'Widowed',
            'familyRole' => 'Parent of Household Head',
            'educationalAttainment' => 'Junior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Unemployed',
            'monthlyIncome' => 'None',
            'ageClassification' => 'SC',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 9
        Resident::create([
            'id' => '25',
            'residentID' => 'RES-00009',
            'firstName' => 'Emily',
            'middleName' => 'Smith',
            'lastName' => 'Doe',
            'dateOfBirth' => '1997-10-09',
            'contactNumber' => '09876543211',
            'email' => 'residentbpms@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'P',
            'pregnancyClassification'=>'P',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 11
        Resident::create([
            'id' => '26',
            'residentID' => 'RES-00009',
            'firstName' => 'Emily',
            'middleName' => 'Smith',
            'lastName' => 'Doe',
            'dateOfBirth' => '1997-10-09',
            'contactNumber' => '09876543211',
            'email' => 'residentbpms@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'P',
            'pregnancyClassification'=>'P',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 13
        Resident::create([
            'id' => '27',
            'residentID' => 'RES-00009',
            'firstName' => 'Emily',
            'middleName' => 'Smith',
            'lastName' => 'Doe',
            'dateOfBirth' => '1997-10-09',
            'contactNumber' => '09876543211',
            'email' => 'residentbpms@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'PP',
            'ageClassification' => 'PP',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '28',
            'residentID' => 'RES-00010',
            'firstName' => 'Janice',
            'middleName' => 'Smith',
            'lastName' => 'Doe',
            'dateOfBirth' => '2024-1-03',
            'contactNumber' => '09876543211',
            'email' => 'residentbpms@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'Undergraduate',
            'gender' => 'F',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'N',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 14
        Resident::create([
            'id' => '29',
            'residentID' => 'RES-00011',
            'firstName' => 'Zen Christopher',
            'middleName' => 'Camp',
            'lastName' => 'Alonso',
            'dateOfBirth' => '2010-03-14',
            'contactNumber' => '09876543211',
            'email' => 'mariekylec@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Elementary Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '30',
            'residentID' => 'RES-00012',
            'firstName' => 'Milo',
            'middleName' => 'Camp',
            'lastName' => 'Alonso',
            'dateOfBirth' => '1991-06-04',
            'contactNumber' => '09876543211',
            'email' => 'mariekylec@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Junior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Tindera',
            'monthlyIncome' => 'less than 9,100',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 15
        Resident::create([
            'id' => '31',
            'residentID' => 'RES-00011',
            'firstName' => 'Zen Christopher',
            'middleName' => 'Camp',
            'lastName' => 'Alonso',
            'dateOfBirth' => '2010-03-14',
            'contactNumber' => '09876543211',
            'email' => 'mariekylec@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Elementary Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '32',
            'residentID' => 'RES-00012',
            'firstName' => 'Milo',
            'middleName' => 'Camp',
            'lastName' => 'Alonso',
            'dateOfBirth' => '1991-06-04',
            'contactNumber' => '09876543211',
            'email' => 'mariekylec@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Junior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Tindera',
            'monthlyIncome' => 'less than 9,100',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 16
        Resident::create([
            'id' => '33',
            'residentID' => 'RES-00013',
            'firstName' => 'Maria',
            'middleName' => 'Marie',
            'lastName' => 'Magdalene',
            'dateOfBirth' => '2000-10-09',
            'contactNumber' => '09876543211',
            'email' => 'mariea@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Cashier',
            'monthlyIncome' => 'less than 9,100',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 17
        Resident::create([
            'id' => '34',
            'residentID' => 'RES-00013',
            'firstName' => 'Maria',
            'middleName' => 'Marie',
            'lastName' => 'Magdalene',
            'dateOfBirth' => '2000-10-09',
            'contactNumber' => '09876543211',
            'email' => 'mariea@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Developer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 18
        Resident::create([
            'id' => '35',
            'residentID' => 'RES-00013',
            'firstName' => 'Maria',
            'middleName' => 'Marie',
            'lastName' => 'Magdalene',
            'dateOfBirth' => '2000-10-09',
            'contactNumber' => '09876543211',
            'email' => 'mariea@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Developer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 19
        Resident::create([
            'id' => '36',
            'residentID' => 'RES-00014',
            'firstName' => 'Peter',
            'middleName' => 'Benjamin',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Architect',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '37',
            'residentID' => 'RES-00015',
            'firstName' => 'Mary Jane',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-4-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Principal',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '38',
            'residentID' => 'RES-00016',
            'firstName' => 'Pedro Pascal',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '2012-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 20
        Resident::create([
            'id' => '39',
            'residentID' => 'RES-00014',
            'firstName' => 'Peter',
            'middleName' => 'Benjamin',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Architect',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '40',
            'residentID' => 'RES-00015',
            'firstName' => 'Mary Jane',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-4-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Principal',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '41',
            'residentID' => 'RES-00016',
            'firstName' => 'Pedro Pascal',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '2012-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        
        //houseID 20
        Resident::create([
            'id' => '42',
            'residentID' => 'RES-00014',
            'firstName' => 'Peter',
            'middleName' => 'Benjamin',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Architect',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '43',
            'residentID' => 'RES-00015',
            'firstName' => 'Mary Jane',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-4-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Principal',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '44',
            'residentID' => 'RES-00016',
            'firstName' => 'Pedro Pascal',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '2012-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);



















        Resident::create([
            'id' => '45',
            'residentID' => 'RES-00019',
            'firstName' => 'Horbs',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '2001-11-18',
            'contactNumber' => '1234567890',
            'email' => 'horeb@bpms.com',
            'maritalStatus' => 'Married',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '40000',
            'ageClassification' => 'AB',
        ]);

        Resident::create([
            'id' => '46',
            'residentID' => 'RES-00020',
            'firstName' => 'Mark',
            'middleName' => 'Sola',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '1980-01-27',
            'contactNumber' => '0999913125',
            'email' => 'marktabangon@gmail.com',
            'maritalStatus' => 'Married',
            'gender' => 'M',
            'occupation' => 'Teacher',
            'monthlyIncome' => '20000',
            'ageClassification' => 'AB',
        ]);

        Resident::create([
            'id' => '47',
            'residentID' => 'RES-00021',
            'firstName' => 'Juniper',
            'middleName' => 'Lela',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '1982-03-17',
            'contactNumber' => '0999819478',
            'email' => 'junilela@gmail.com',
            'maritalStatus' => 'Married',
            'gender' => 'F',
            'occupation' => 'Accountant',
            'monthlyIncome' => '17000',
            'ageClassification' => 'WRA',
        ]);

        Resident::create([
            'id' => '48',
            'residentID' => 'RES-00022',
            'firstName' => 'Earl',
            'middleName' => 'Fuente',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '1943-06-12',
            'contactNumber' => '1234567890',
            'email' => 'earltabangon@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Unemployed',
            'monthlyIncome' => '0',
            'ageClassification' => 'SC',
        ]);

        Resident::create([
            'id' => '49',
            'residentID' => 'RES-00023',
            'firstName' => 'Leslie John',
            'middleName' => 'Lela',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '2005-02-13',
            'contactNumber' => '1234567890',
            'email' => 'leslietabangon@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => '0',
            'ageClassification' => 'A',
        ]);

        Resident::create([
            'id' => '50',
            'residentID' => 'RES-00024',
            'firstName' => 'Ron',
            'middleName' => 'Lela',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '2008-01-28',
            'contactNumber' => '1234567890',
            'email' => 'rontabangon@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => '0',
            'ageClassification' => 'A',
        ]);
        

    }
}
