<?php

namespace Database\Seeders;

use App\Models\Resident;
use Illuminate\Database\Seeder;

class ResidentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Resident::create([
            'id' => '1',
            'residentID' => 'RES-00001',
            'firstName' => 'Admin',
            'middleName' => 'PCSZ',
            'lastName' => 'Capstone',
            'dateOfBirth' => '2000-01-01',
            'contactNumber' => '09876543210',
            'email' => 'adminPersonalEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Account Manager',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
            ]);
        
        // houseID 2
        Resident::create([
            'id' => '4',
            'residentID' => 'RES-00002',
            'firstName' => 'Andres',
            'middleName' => 'Jefferson',
            'lastName' => 'Morales',
            'dateOfBirth' => '1970-05-07',
            'contactNumber' => '09876543211',
            'email' => 'andres@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Firefighter',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '3',
            'residentID' => 'RES-00003',
            'firstName' => 'Rio',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '1980-03-07',
            'contactNumber' => '09876543111',
            'email' => 'rio@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '2',
            'residentID' => 'RES-00004',
            'firstName' => 'Miles',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '2000-02-07',
            'contactNumber' => '09876541111',
            'email' => 'morales@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Barangay Health Worker',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 3
        Resident::create([
            'id' => '5',
            'residentID' => 'RES-00002',
            'firstName' => 'Andres',
            'middleName' => 'Jefferson',
            'lastName' => 'Morales',
            'dateOfBirth' => '1970-05-07',
            'contactNumber' => '09876543211',
            'email' => 'andres@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Firefighter',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '6',
            'residentID' => 'RES-00003',
            'firstName' => 'Rio',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '1980-03-07',
            'contactNumber' => '09876543111',
            'email' => 'rio@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '7',
            'residentID' => 'RES-00004',
            'firstName' => 'Miles',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '2000-02-07',
            'contactNumber' => '09876541111',
            'email' => 'morales@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Barangay Health Worker',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 4
        Resident::create([
            'id' => '8',
            'residentID' => 'RES-00002',
            'firstName' => 'Andres',
            'middleName' => 'Jefferson',
            'lastName' => 'Morales',
            'dateOfBirth' => '1970-05-07',
            'contactNumber' => '09876543211',
            'email' => 'andres@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Firefighter',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '9',
            'residentID' => 'RES-00003',
            'firstName' => 'Rio',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '1980-03-07',
            'contactNumber' => '09876543111',
            'email' => 'rio@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '10',
            'residentID' => 'RES-00004',
            'firstName' => 'Miles',
            'middleName' => 'Davis',
            'lastName' => 'Morales',
            'dateOfBirth' => '2000-02-07',
            'contactNumber' => '09876541111',
            'email' => 'morales@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Barangay Health Worker',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '11',
            'residentID' => 'RES-00005',
            'firstName' => 'Joseph',
            'middleName' => 'Jefferson',
            'lastName' => 'Morales',
            'dateOfBirth' => '2008-02-07',
            'contactNumber' => '09876533211',
            'email' => 'joseph@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Unemployed',
            'monthlyIncome' => 'None',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 5
        Resident::create([
            'id' => '12',
            'residentID' => 'RES-00006',
            'firstName' => 'Gwen',
            'middleName' => 'Maxine',
            'lastName' => 'Stacy',
            'dateOfBirth' => '2001-02-20',
            'contactNumber' => '09876543212',
            'email' => 'stacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Secretary',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '13',
            'residentID' => 'RES-00007',
            'firstName' => 'James',
            'middleName' => 'Madelyn',
            'lastName' => 'Stacy',
            'dateOfBirth' => '1997-02-20',
            'contactNumber' => '09876543212',
            'email' => 'jamestacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 6
        Resident::create([
            'id' => '14',
            'residentID' => 'RES-00006',
            'firstName' => 'Gwen',
            'middleName' => 'Maxine',
            'lastName' => 'Stacy',
            'dateOfBirth' => '2001-02-20',
            'contactNumber' => '09876543212',
            'email' => 'stacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Secretary',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '15',
            'residentID' => 'RES-00007',
            'firstName' => 'James',
            'middleName' => 'Madelyn',
            'lastName' => 'Stacy',
            'dateOfBirth' => '1997-02-20',
            'contactNumber' => '09876543212',
            'email' => 'jamestacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 7
        Resident::create([
            'id' => '16',
            'residentID' => 'RES-00006',
            'firstName' => 'Gwen',
            'middleName' => 'Maxine',
            'lastName' => 'Stacy',
            'dateOfBirth' => '2001-02-20',
            'contactNumber' => '09876543212',
            'email' => 'stacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Secretary',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '17',
            'residentID' => 'RES-00007',
            'firstName' => 'James',
            'middleName' => 'Madelyn',
            'lastName' => 'Stacy',
            'dateOfBirth' => '1997-02-20',
            'contactNumber' => '09876543212',
            'email' => 'jamestacy@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 8
        Resident::create([
            'id' => '18',
            'residentID' => 'RES-00008',
            'firstName' => 'Francine',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'francine@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Captain',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '19',
            'residentID' => 'RES-00009',
            'firstName' => 'Juan',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'frances@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 10
        Resident::create([
            'id' => '20',
            'residentID' => 'RES-00008',
            'firstName' => 'Francine',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'francine@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Captain',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '21',
            'residentID' => 'RES-00009',
            'firstName' => 'Juan',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'frances@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 12
        Resident::create([
            'id' => '22',
            'residentID' => 'RES-00008',
            'firstName' => 'Francine',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'francine@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Barangay Captain',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '23',
            'residentID' => 'RES-00009',
            'firstName' => 'Juan',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '2000-11-11',
            'contactNumber' => '09876543211',
            'email' => 'frances@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '24',
            'residentID' => 'RES-00010',
            'firstName' => 'Frances',
            'middleName' => 'Marie',
            'lastName' => 'Kyle',
            'dateOfBirth' => '1960-11-11',
            'contactNumber' => '09876543211',
            'email' => 'francesca@gmail.com',
            'maritalStatus' => 'Widowed',
            'familyRole' => 'Parent of Household Head',
            'educationalAttainment' => 'Junior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Unemployed',
            'monthlyIncome' => 'None',
            'ageClassification' => 'SC',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 9
        Resident::create([
            'id' => '25',
            'residentID' => 'RES-00011',
            'firstName' => 'Emily',
            'middleName' => 'Smith',
            'lastName' => 'Doe',
            'dateOfBirth' => '1997-10-09',
            'contactNumber' => '09876543211',
            'email' => 'residentbpms@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'P',
            'pregnancyClassification'=>'P',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 11
        Resident::create([
            'id' => '26',
            'residentID' => 'RES-00011',
            'firstName' => 'Emily',
            'middleName' => 'Smith',
            'lastName' => 'Doe',
            'dateOfBirth' => '1997-10-09',
            'contactNumber' => '09876543211',
            'email' => 'residentbpms@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'P',
            'pregnancyClassification'=>'P',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 13
        Resident::create([
            'id' => '27',
            'residentID' => 'RES-00011',
            'firstName' => 'Emily',
            'middleName' => 'Smith',
            'lastName' => 'Doe',
            'dateOfBirth' => '1997-10-09',
            'contactNumber' => '09876543211',
            'email' => 'residentbpms@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'PP',
            'ageClassification' => 'PP',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '28',
            'residentID' => 'RES-00012',
            'firstName' => 'Janice',
            'middleName' => 'Smith',
            'lastName' => 'Doe',
            'dateOfBirth' => '2024-1-03',
            'contactNumber' => '09876543211',
            'email' => 'residentbpms@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'Undergraduate',
            'gender' => 'F',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'N',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 14
        Resident::create([
            'id' => '29',
            'residentID' => 'RES-00013',
            'firstName' => 'Zen Christopher',
            'middleName' => 'Camp',
            'lastName' => 'Alonso',
            'dateOfBirth' => '2010-03-14',
            'contactNumber' => '09876543211',
            'email' => 'mariekylec@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Elementary Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '30',
            'residentID' => 'RES-00014',
            'firstName' => 'Milo',
            'middleName' => 'Camp',
            'lastName' => 'Alonso',
            'dateOfBirth' => '1991-06-04',
            'contactNumber' => '09876543211',
            'email' => 'mariekylec@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Junior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Tindera',
            'monthlyIncome' => 'less than 9,100',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 15
        Resident::create([
            'id' => '31',
            'residentID' => 'RES-00013',
            'firstName' => 'Zen Christopher',
            'middleName' => 'Camp',
            'lastName' => 'Alonso',
            'dateOfBirth' => '2010-03-14',
            'contactNumber' => '09876543211',
            'email' => 'mariekylec@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Elementary Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '32',
            'residentID' => 'RES-00014',
            'firstName' => 'Milo',
            'middleName' => 'Camp',
            'lastName' => 'Alonso',
            'dateOfBirth' => '1991-06-04',
            'contactNumber' => '09876543211',
            'email' => 'mariekylec@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Junior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Tindera',
            'monthlyIncome' => 'less than 9,100',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 16
        Resident::create([
            'id' => '33',
            'residentID' => 'RES-00015',
            'firstName' => 'Maria',
            'middleName' => 'Marie',
            'lastName' => 'Magdalene',
            'dateOfBirth' => '2000-10-09',
            'contactNumber' => '09876543211',
            'email' => 'mariea@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Cashier',
            'monthlyIncome' => 'less than 9,100',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 17
        Resident::create([
            'id' => '34',
            'residentID' => 'RES-00015',
            'firstName' => 'Maria',
            'middleName' => 'Marie',
            'lastName' => 'Magdalene',
            'dateOfBirth' => '2000-10-09',
            'contactNumber' => '09876543211',
            'email' => 'mariea@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Developer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        //houseID 18
        Resident::create([
            'id' => '35',
            'residentID' => 'RES-00015',
            'firstName' => 'Maria',
            'middleName' => 'Marie',
            'lastName' => 'Magdalene',
            'dateOfBirth' => '2000-10-09',
            'contactNumber' => '09876543211',
            'email' => 'mariea@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Developer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 19
        Resident::create([
            'id' => '36',
            'residentID' => 'RES-00016',
            'firstName' => 'Peter',
            'middleName' => 'Benjamin',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Architect',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '37',
            'residentID' => 'RES-00017',
            'firstName' => 'Mary Jane',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-4-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Principal',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '38',
            'residentID' => 'RES-00018',
            'firstName' => 'Pedro Pascal',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '2012-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //houseID 20
        Resident::create([
            'id' => '39',
            'residentID' => 'RES-00016',
            'firstName' => 'Peter',
            'middleName' => 'Benjamin',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Architect',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '40',
            'residentID' => 'RES-00017',
            'firstName' => 'Mary Jane',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-4-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Principal',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '41',
            'residentID' => 'RES-00018',
            'firstName' => 'Pedro Pascal',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '2012-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        
        //houseID 21
        Resident::create([
            'id' => '42',
            'residentID' => 'RES-00016',
            'firstName' => 'Peter',
            'middleName' => 'Benjamin',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Architect',
            'monthlyIncome' => '109,200 - 182,000',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '43',
            'residentID' => 'RES-00017',
            'firstName' => 'Mary Jane',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-4-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Principal',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'WRA',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        Resident::create([
            'id' => '44',
            'residentID' => 'RES-00018',
            'firstName' => 'Pedro Pascal',
            'middleName' => 'Jones',
            'lastName' => 'Parker',
            'dateOfBirth' => '2012-10-09',
            'contactNumber' => '09876543211',
            'email' => 'parker@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);
        Resident::create([
            'id' => '45',
            'residentID' => 'RES-00042',
            'firstName' => 'Pascal',
            'middleName' => 'Benjamin',
            'lastName' => 'Parker',
            'dateOfBirth' => '1980-10-09',
            'contactNumber' => '09876543211',
            'email' => 'pascal@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'AB',
            'dateOfDeath' => null,
            'createdBy' => 2,
            'revisedBy' => 2,
        ]);

        //22 - 46 47 48
        Resident::create([
            'id' => '46',
            'residentID' => 'RES-00019',
            'firstName' => 'John Jacob',
            'middleName' => 'Ang',
            'lastName' => 'Black',
            'dateOfBirth' => '2000-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '47',
            'residentID' => 'RES-00020',
            'firstName' => 'Dorothy',
            'middleName' => 'Ang',
            'lastName' => 'Black',
            'dateOfBirth' => '1980-12-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '48',
            'residentID' => 'RES-00021',
            'firstName' => 'Billy',
            'middleName' => 'Ang',
            'lastName' => 'Black',
            'dateOfBirth' => '1970-10-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
        ]);

        //23 - 49 50 51
        Resident::create([
            'id' => '49',
            'residentID' => 'RES-00019',
            'firstName' => 'John Jacob',
            'middleName' => 'Ang',
            'lastName' => 'Black',
            'dateOfBirth' => '2000-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '50',
            'residentID' => 'RES-00020',
            'firstName' => 'Dorothy',
            'middleName' => 'Ang',
            'lastName' => 'Black',
            'dateOfBirth' => '1980-12-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '51',
            'residentID' => 'RES-00021',
            'firstName' => 'Billy',
            'middleName' => 'Ang',
            'lastName' => 'Black',
            'dateOfBirth' => '1970-10-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
        ]);

        //24 - 52 53 54
        Resident::create([
            'id' => '52',
            'residentID' => 'RES-00019',
            'firstName' => 'John Jacob',
            'middleName' => 'Ang',
            'lastName' => 'Black',
            'dateOfBirth' => '2000-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '53',
            'residentID' => 'RES-00020',
            'firstName' => 'Dorothy',
            'middleName' => 'Ang',
            'lastName' => 'Black',
            'dateOfBirth' => '1980-12-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '54',
            'residentID' => 'RES-00021',
            'firstName' => 'Billy',
            'middleName' => 'Ang',
            'lastName' => 'Black',
            'dateOfBirth' => '1970-10-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse Household Head',
            'educationalAttainment' => 'UnderGraduate',
            'gender' => 'M',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
        ]);

        //25 - 55 56 57 58
        Resident::create([
            'id' => '55',
            'residentID' => 'RES-00022',
            'firstName' => 'Edward',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '2000-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Doctor',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '56',
            'residentID' => 'RES-00023',
            'firstName' => 'Carlisle',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '1960-11-2',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Parent of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Retired',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'SC',
        ]);
        Resident::create([
            'id' => '57',
            'residentID' => 'RES-00024',
            'firstName' => 'Esme',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '1970-7-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Parent of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '58',
            'residentID' => 'RES-00025',
            'firstName' => 'Alice',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '2010-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'A',
        ]);

        //26 - 59 60 61 62
        Resident::create([
            'id' => '59',
            'residentID' => 'RES-00022',
            'firstName' => 'Edward',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '2000-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '60',
            'residentID' => 'RES-00023',
            'firstName' => 'Carlisle',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '1960-11-2',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Parent of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Retired',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'SC',
        ]);
        Resident::create([
            'id' => '61',
            'residentID' => 'RES-00024',
            'firstName' => 'Esme',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '1970-7-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Parent of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '62',
            'residentID' => 'RES-00025',
            'firstName' => 'Alice',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '2010-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'A',
        ]);

        //27 - 63 64 65 66
        Resident::create([
            'id' => '63',
            'residentID' => 'RES-00022',
            'firstName' => 'Edward',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '2000-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '64',
            'residentID' => 'RES-00023',
            'firstName' => 'Carlisle',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '1960-11-2',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Parent of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Retired',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'SC',
        ]);
        Resident::create([
            'id' => '65',
            'residentID' => 'RES-00024',
            'firstName' => 'Esme',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '1970-7-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Parent of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Doctor',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '66',
            'residentID' => 'RES-00025',
            'firstName' => 'Alice',
            'middleName' => 'Santos',
            'lastName' => 'Cullen',
            'dateOfBirth' => '2010-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'A',
        ]);

        //28 - 67 68 69
        Resident::create([
            'id' => '67',
            'residentID' => 'RES-00026',
            'firstName' => 'Bella',
            'middleName' => 'Maria',
            'lastName' => 'Swan',
            'dateOfBirth' => '1990-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '68',
            'residentID' => 'RES-00027',
            'firstName' => 'Renesmee',
            'middleName' => 'Maria',
            'lastName' => 'Swan',
            'dateOfBirth' => '2018-7-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'U',
        ]);
        Resident::create([
            'id' => '69',
            'residentID' => 'RES-00028',
            'firstName' => 'Marco Polo',
            'middleName' => 'Maria',
            'lastName' => 'Swan',
            'dateOfBirth' => '1990-6-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Construction Worker',
            'monthlyIncome' => 'less than 9,100',
            'ageClassification' => 'AB',
        ]);

        //29 70 71 72
        Resident::create([
            'id' => '70',
            'residentID' => 'RES-00026',
            'firstName' => 'Bella',
            'middleName' => 'Maria',
            'lastName' => 'Swan',
            'dateOfBirth' => '1990-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '71',
            'residentID' => 'RES-00027',
            'firstName' => 'Renesmee',
            'middleName' => 'Maria',
            'lastName' => 'Swan',
            'dateOfBirth' => '2018-7-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
        ]);
        Resident::create([
            'id' => '72',
            'residentID' => 'RES-00028',
            'firstName' => 'Marco Polo',
            'middleName' => 'Maria',
            'lastName' => 'Swan',
            'dateOfBirth' => '1990-6-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Construction Worker',
            'monthlyIncome' => 'less than 9,100',
            'ageClassification' => 'AB',
        ]);

        //30 - 73 74 75
        Resident::create([
            'id' => '73',
            'residentID' => 'RES-00026',
            'firstName' => 'Bella',
            'middleName' => 'Maria',
            'lastName' => 'Swan',
            'dateOfBirth' => '1990-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '74',
            'residentID' => 'RES-00027',
            'firstName' => 'Renesmee',
            'middleName' => 'Maria',
            'lastName' => 'Swan',
            'dateOfBirth' => '2018-7-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'None',
            'monthlyIncome' => 'None',
            'ageClassification' => 'B',
        ]);
        Resident::create([
            'id' => '75',
            'residentID' => 'RES-00028',
            'firstName' => 'Marco Polo',
            'middleName' => 'Maria',
            'lastName' => 'Swan',
            'dateOfBirth' => '1990-6-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Construction Worker',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
        ]);


        //31 - 76 77 78 79 80
        Resident::create([
            'id' => '76',
            'residentID' => 'RES-00029',
            'firstName' => 'Horbs',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '77',
            'residentID' => 'RES-00030',
            'firstName' => 'Lourdes Marie Kyle',
            'middleName' => 'Campomanes',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-11-11',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Web Developer',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '78',
            'residentID' => 'RES-00031',
            'firstName' => 'Teddy Bartlett',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-1-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '79',
            'residentID' => 'RES-00032',
            'firstName' => 'Nikolai Tumapon',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-5-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Relative',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '80',
            'residentID' => 'RES-00033',
            'firstName' => 'Van Vanguardia',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-7-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Relative',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);

        //32 81 82 83 84 85
        Resident::create([
            'id' => '81',
            'residentID' => 'RES-00029',
            'firstName' => 'Horbs',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '82',
            'residentID' => 'RES-00030',
            'firstName' => 'Lourdes Marie Kyle',
            'middleName' => 'Campomanes',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-11-11',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Web Developer',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '83',
            'residentID' => 'RES-00031',
            'firstName' => 'Teddy Bartlett',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-1-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '84',
            'residentID' => 'RES-00032',
            'firstName' => 'Nikolai Tumapon',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-5-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Relative',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '85',
            'residentID' => 'RES-00033',
            'firstName' => 'Van Vanguardia',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-7-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Relative',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);


        //33 86 87 88 89 90
        Resident::create([
            'id' => '86',
            'residentID' => 'RES-00029',
            'firstName' => 'Horbs',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-11-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '87',
            'residentID' => 'RES-00030',
            'firstName' => 'Lourdes Marie Kyle',
            'middleName' => 'Campomanes',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-11-11',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Web Developer',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '88',
            'residentID' => 'RES-00031',
            'firstName' => 'Teddy Bartlett',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-1-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '89',
            'residentID' => 'RES-00032',
            'firstName' => 'Nikolai Tumapon',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-5-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Relative',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '90',
            'residentID' => 'RES-00033',
            'firstName' => 'Van Vanguardia',
            'middleName' => 'Bars',
            'lastName' => 'Mendoza',
            'dateOfBirth' => '1990-7-18',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Relative',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'IT Programmer',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);


        //34 91 92 93 94 95
        Resident::create([
            'id' => '91',
            'residentID' => 'RES-00034',
            'firstName' => 'Mark',
            'middleName' => 'Sola',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '1980-01-27',
            'contactNumber' => '0999913125',
            'email' => 'marktabangon@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '92',
            'residentID' => 'RES-00035',
            'firstName' => 'Juniper',
            'middleName' => 'Lela',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '1982-03-17',
            'contactNumber' => '0999819478',
            'email' => 'junilela@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Accountant',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '93',
            'residentID' => 'RES-00036',
            'firstName' => 'Earl',
            'middleName' => 'Fuente',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '1943-06-12',
            'contactNumber' => '09876541230',
            'email' => 'earltabangon@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Grandparent of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Unemployed',
            'monthlyIncome' => 'None',
            'ageClassification' => 'SC',
        ]);
        Resident::create([
            'id' => '94',
            'residentID' => 'RES-00037',
            'firstName' => 'Leslie John',
            'middleName' => 'Lela',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '2005-02-13',
            'contactNumber' => '09876541230',
            'email' => 'leslietabangon@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'Junior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'A',
        ]);
        Resident::create([
            'id' => '95',
            'residentID' => 'RES-00038',
            'firstName' => 'Ron',
            'middleName' => 'Lela',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '2008-01-28',
            'contactNumber' => '09876541230',
            'email' => 'rontabangon@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'Elementary Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'A',
        ]);
        

        //35 96 97 98 99 100
        Resident::create([
            'id' => '96',
            'residentID' => 'RES-00034',
            'firstName' => 'Mark',
            'middleName' => 'Sola',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '1980-01-27',
            'contactNumber' => '0999913125',
            'email' => 'marktabangon@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Teacher',
            'monthlyIncome' => '9,100 - 18,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '97',
            'residentID' => 'RES-00035',
            'firstName' => 'Juniper',
            'middleName' => 'Lela',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '1982-03-17',
            'contactNumber' => '0999819478',
            'email' => 'junilela@gmail.com',
            'maritalStatus' => 'Married',
            'familyRole' => 'Spouse of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'F',
            'occupation' => 'Accountant',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'WRA',
        ]);
        Resident::create([
            'id' => '98',
            'residentID' => 'RES-00036',
            'firstName' => 'Earl',
            'middleName' => 'Fuente',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '1943-06-12',
            'contactNumber' => '09876541230',
            'email' => 'earltabangon@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Grandparent of Household Head',
            'educationalAttainment' => 'College Graduate',
            'gender' => 'M',
            'occupation' => 'Unemployed',
            'monthlyIncome' => 'None',
            'ageClassification' => 'SC',
        ]);
        Resident::create([
            'id' => '99',
            'residentID' => 'RES-00037',
            'firstName' => 'Leslie John',
            'middleName' => 'Lela',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '2005-02-13',
            'contactNumber' => '09876541230',
            'email' => 'leslietabangon@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'Junior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'A',
        ]);
        Resident::create([
            'id' => '100',
            'residentID' => 'RES-00038',
            'firstName' => 'Ron',
            'middleName' => 'Lela',
            'lastName' => 'Tabangon',
            'dateOfBirth' => '2008-01-28',
            'contactNumber' => '09876541230',
            'email' => 'rontabangon@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Child of Household Head',
            'educationalAttainment' => 'Elementary Graduate',
            'gender' => 'M',
            'occupation' => 'Student',
            'monthlyIncome' => 'None',
            'ageClassification' => 'A',
        ]);


        //36 101 102 103
        Resident::create([
            'id' => '101',
            'residentID' => 'RES-00039',
            'firstName' => 'Owen',
            'middleName' => 'Lela',
            'lastName' => 'Zammy',
            'dateOfBirth' => '1980-01-28',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Singer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '102',
            'residentID' => 'RES-00040',
            'firstName' => 'Ollie',
            'middleName' => 'Lela',
            'lastName' => 'Zammy',
            'dateOfBirth' => '1981-08-28',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Dancer',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '103',
            'residentID' => 'RES-00041',
            'firstName' => 'Marjorie',
            'middleName' => 'Lela',
            'lastName' => 'Zammy',
            'dateOfBirth' => '1940-08-28',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Grandparent of Household Head',
            'educationalAttainment' => 'Elementary Graduate',
            'gender' => 'M',
            'occupation' => 'Retired',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'SC',
        ]);


        //37 103 104 105
        Resident::create([
            'id' => '104',
            'residentID' => 'RES-00039',
            'firstName' => 'Owen',
            'middleName' => 'Lela',
            'lastName' => 'Zammy',
            'dateOfBirth' => '1980-01-28',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Singer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '105',
            'residentID' => 'RES-00040',
            'firstName' => 'Ollie',
            'middleName' => 'Lela',
            'lastName' => 'Zammy',
            'dateOfBirth' => '1981-08-28',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Dancer',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '106',
            'residentID' => 'RES-00041',
            'firstName' => 'Marjorie',
            'middleName' => 'Lela',
            'lastName' => 'Zammy',
            'dateOfBirth' => '1940-08-28',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Grandparent of Household Head',
            'educationalAttainment' => 'Elementary Graduate',
            'gender' => 'M',
            'occupation' => 'Retired',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'SC',
        ]);


        //38 106 107 108
        Resident::create([
            'id' => '107',
            'residentID' => 'RES-00039',
            'firstName' => 'Owen',
            'middleName' => 'Lela',
            'lastName' => 'Zammy',
            'dateOfBirth' => '1980-01-28',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'M',
            'occupation' => 'Singer',
            'monthlyIncome' => '36,400 - 63,700',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '108',
            'residentID' => 'RES-00040',
            'firstName' => 'Ollie',
            'middleName' => 'Lela',
            'lastName' => 'Zammy',
            'dateOfBirth' => '1981-08-28',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Sibling of Household Head',
            'educationalAttainment' => 'Senior High School Graduate',
            'gender' => 'F',
            'occupation' => 'Dancer',
            'monthlyIncome' => '63,700 - 109,200',
            'ageClassification' => 'AB',
        ]);
        Resident::create([
            'id' => '109',
            'residentID' => 'RES-00041',
            'firstName' => 'Marjorie',
            'middleName' => 'Lela',
            'lastName' => 'Zammy',
            'dateOfBirth' => '1940-08-28',
            'contactNumber' => '09876541230',
            'email' => 'genericEmail@gmail.com',
            'maritalStatus' => 'Single',
            'familyRole' => 'Grandparent of Household Head',
            'educationalAttainment' => 'Elementary Graduate',
            'gender' => 'M',
            'occupation' => 'Retired',
            'monthlyIncome' => '18,200 - 36,400',
            'ageClassification' => 'SC',
        ]);


        //39


        //40

        
        //41
        //42
        //43
        //44
        //45
        //46
        //47
        //48
        //49
        //50
        //51
        //52
        //53
        //54
        //55
        //56
        //57
        //58
        //59
        //60
        //61
        //62
        //63
        //64
        //65
        //66
        //67
        //68
        //69
        //70
        //71
        //72
        //73
        //74
        //75
        //76
        //77
        //78
        //79
        //80
        //81
        //82
        //83
        //84
        //85
        //86
        //87
        //88
        //89
        //90
        //91
        //92
        //93
        //94
        //95
        //96
        //97
        //98
        //99
        //100
        //101
        //102
        //103
        //104
        //105
        //106
        //107
        //108
        //109
        //110
        //111
        //112
        //113
        //114
        //115
        //116
        //117
        //118
        //119
        //120
        //121
        //122
        //123
        //124
        //125
        //126
        //127
        //128
        //129
        //130
        //131

    }
}
