<?php

namespace Database\Seeders;

use App\Models\ResidentList;
use Illuminate\Database\Seeder;

class ResidentListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Admin
        ResidentList::create([
            'residentID'=>'1',
            'houseID'=>'1',
            'houseNumber'=>1,
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //Andres
        ResidentList::create([
            'residentID' => '2',
            'houseID' => '2',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Rio
        ResidentList::create([
            'residentID' => '3',
            'houseID' => '2',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Miles
        ResidentList::create([
            'residentID' => '4',
            'houseID' => '2',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Andres
        ResidentList::create([
            'residentID' => '5',
            'houseID' => '3',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Rio
        ResidentList::create([
            'residentID' => '6',
            'houseID' => '3',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Miles
        ResidentList::create([
            'residentID' => '7',
            'houseID' => '3',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Andres
        ResidentList::create([
            'residentID' => '8',
            'houseID' => '4',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Rio
        ResidentList::create([
            'residentID' => '9',
            'houseID' => '4',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Miles
        ResidentList::create([
            'residentID' => '10',
            'houseID' => '4',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Joseph
        ResidentList::create([
            'residentID' => '11',
            'houseID' => '4',
            'houseNumber'=>'1',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //Gwen
        ResidentList::create([
            'residentID' => '12',
            'houseID' => '5',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //James
        ResidentList::create([
            'residentID' => '13',
            'houseID' => '5',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Gwen
        ResidentList::create([
            'residentID' => '14',
            'houseID' => '6',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //James
        ResidentList::create([
            'residentID' => '15',
            'houseID' => '6',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Gwen
        ResidentList::create([
            'residentID' => '16',
            'houseID' => '7',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //James
        ResidentList::create([
            'residentID' => '17',
            'houseID' => '7',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //Francine
        ResidentList::create([
            'residentID'=>'18',
            'houseID'=>'8',
            'houseNumber'=>'3A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //Juan
        ResidentList::create([
            'residentID'=>'19',
            'houseID'=>'8',
            'houseNumber'=>'3A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Francine
        ResidentList::create([
            'residentID'=>'20',
            'houseID'=>'10',
            'houseNumber'=>'3A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //Juan
        ResidentList::create([
            'residentID'=>'21',
            'houseID'=>'10',
            'houseNumber'=>'3A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Francine
        ResidentList::create([
            'residentID'=>'22',
            'houseID'=>'12',
            'houseNumber'=>'3A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //Juan
        ResidentList::create([
            'residentID'=>'23',
            'houseID'=>'12',
            'houseNumber'=>'3A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Frances
        ResidentList::create([
            'residentID'=>'24',
            'houseID'=>'12',
            'houseNumber'=>'3A',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //Emily
        ResidentList::create([
            'residentID'=>'25',
            'houseID'=>'9',
            'houseNumber'=>'3B',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'26',
            'houseID'=>'11',
            'houseNumber'=>'3B',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'27',
            'houseID'=>'13',
            'houseNumber'=>'3B',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Janice
        ResidentList::create([
            'residentID'=>'28',
            'houseID'=>'13',
            'houseNumber'=>'3B',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //Zen
        ResidentList::create([
            'residentID'=>'29',
            'houseID'=>'14',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Milo
        ResidentList::create([
            'residentID'=>'30',
            'houseID'=>'14',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Zen
        ResidentList::create([
            'residentID'=>'31',
            'houseID'=>'15',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Milo
        ResidentList::create([
            'residentID'=>'32',
            'houseID'=>'15',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Emily
        ResidentList::create([
            'residentID'=>'33',
            'houseID'=>'16',
            'houseNumber'=>'5',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'34',
            'houseID'=>'17',
            'houseNumber'=>'5',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'35',
            'houseID'=>'18',
            'houseNumber'=>'5',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //Peter
        ResidentList::create([
            'residentID' => '36',
            'houseID' => '19',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //MJ
        ResidentList::create([
            'residentID' => '37',
            'houseID' => '19',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //PedroPascal
        ResidentList::create([
            'residentID'=>'38',
            'houseID'=>'19',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Peter
        ResidentList::create([
            'residentID' => '39',
            'houseID' => '20',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //MJ
        ResidentList::create([
            'residentID' => '40',
            'houseID' => '20',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //PedroPascal
        ResidentList::create([
            'residentID'=>'41',
            'houseID'=>'20',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //Peter
        ResidentList::create([
            'residentID' => '42',
            'houseID' => '21',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //MJ
        ResidentList::create([
            'residentID' => '43',
            'houseID' => '21',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //PedroPascal
        ResidentList::create([
            'residentID'=>'44',
            'houseID'=>'21',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);


        //22 - 46 47 48
        ResidentList::create([
            'residentID'=>'46',
            'houseID'=>'22',
            'houseNumber'=>'2A',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'47',
            'houseID'=>'22',
            'houseNumber'=>'2A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        ResidentList::create([
            'residentID'=>'48',
            'houseID'=>'22',
            'houseNumber'=>'2A',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //23 - 49 50 51
        ResidentList::create([
            'residentID'=>'49',
            'houseID'=>'23',
            'houseNumber'=>'2A',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'50',
            'houseID'=>'23',
            'houseNumber'=>'2A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'51',
            'houseID'=>'23',
            'houseNumber'=>'2A',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //24 - 52 53 54
        ResidentList::create([
            'residentID'=>'52',
            'houseID'=>'24',
            'houseNumber'=>'2A',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'53',
            'houseID'=>'24',
            'houseNumber'=>'2A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'54',
            'houseID'=>'24',
            'houseNumber'=>'2A',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);


        //25 - 55 56 57 58
        ResidentList::create([
            'residentID'=>'55',
            'houseID'=>'25',
            'houseNumber'=>'2B',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'56',
            'houseID'=>'25',
            'houseNumber'=>'2B',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'57',
            'houseID'=>'25',
            'houseNumber'=>'2B',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'58',
            'houseID'=>'25',
            'houseNumber'=>'2B',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //26 - 59 60 61 62
        ResidentList::create([
            'residentID'=>'59',
            'houseID'=>'26',
            'houseNumber'=>'2B',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'60',
            'houseID'=>'26',
            'houseNumber'=>'2B',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'61',
            'houseID'=>'26',
            'houseNumber'=>'2B',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'62',
            'houseID'=>'26',
            'houseNumber'=>'2B',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //27 - 63 64 65 66
        ResidentList::create([
            'residentID'=>'63',
            'houseID'=>'27',
            'houseNumber'=>'2B',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'64',
            'houseID'=>'27',
            'houseNumber'=>'2B',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'65',
            'houseID'=>'27',
            'houseNumber'=>'2B',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'66',
            'houseID'=>'27',
            'houseNumber'=>'2B',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);


        //28 - 67 68 69
        ResidentList::create([
            'residentID'=>'67',
            'houseID'=>'28',
            'houseNumber'=>'2C',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'68',
            'houseID'=>'28',
            'houseNumber'=>'2C',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'69',
            'houseID'=>'28',
            'houseNumber'=>'2C',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //29 70 71 72
        ResidentList::create([
            'residentID'=>'70',
            'houseID'=>'29',
            'houseNumber'=>'2C',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'71',
            'houseID'=>'29',
            'houseNumber'=>'2C',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'72',
            'houseID'=>'29',
            'houseNumber'=>'2C',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //30 - 73 74 75
        ResidentList::create([
            'residentID'=>'73',
            'houseID'=>'30',
            'houseNumber'=>'2C',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'74',
            'houseID'=>'30',
            'houseNumber'=>'2C',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'75',
            'houseID'=>'30',
            'houseNumber'=>'2C',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //31 - 76 77 78 79 80
        ResidentList::create([
            'residentID'=>'76',
            'houseID'=>'31',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'77',
            'houseID'=>'31',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'78',
            'houseID'=>'31',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'79',
            'houseID'=>'31',
            'houseNumber'=>'3',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'80',
            'houseID'=>'31',
            'houseNumber'=>'3',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //32 81 82 83 84 85
        ResidentList::create([
            'residentID'=>'81',
            'houseID'=>'32',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'82',
            'houseID'=>'32',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'83',
            'houseID'=>'32',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'84',
            'houseID'=>'32',
            'houseNumber'=>'3',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'85',
            'houseID'=>'32',
            'houseNumber'=>'3',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //33 86 87 88 89 90
        ResidentList::create([
            'residentID'=>'86',
            'houseID'=>'33',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'87',
            'houseID'=>'33',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'88',
            'houseID'=>'33',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'89',
            'houseID'=>'33',
            'houseNumber'=>'3',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'90',
            'houseID'=>'33',
            'houseNumber'=>'3',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //34 91 92 93 94 95
        ResidentList::create([
            'residentID'=>'91',
            'houseID'=>'34',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'92',
            'houseID'=>'34',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'93',
            'houseID'=>'34',
            'houseNumber'=>'4',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'94',
            'houseID'=>'34',
            'houseNumber'=>'4',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'95',
            'houseID'=>'34',
            'houseNumber'=>'4',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //35 96 97 98 99 100
        ResidentList::create([
            'residentID'=>'96',
            'houseID'=>'35',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'97',
            'houseID'=>'35',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'98',
            'houseID'=>'35',
            'houseNumber'=>'4',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'99',
            'houseID'=>'35',
            'houseNumber'=>'4',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'100',
            'houseID'=>'35',
            'houseNumber'=>'4',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //36 101 102 103
        ResidentList::create([
            'residentID' => '101',
            'houseID' => '36',
            'houseNumber'=>'5',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);   
        ResidentList::create([
            'residentID' => '102',
            'houseID' => '36',
            'houseNumber'=>'5',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);   
        ResidentList::create([
            'residentID' => '103',
            'houseID' => '36',
            'houseNumber'=>'5',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);   
        //37 104 105 106
        ResidentList::create([
            'residentID' => '104',
            'houseID' => '37',
            'houseNumber'=>'5',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);   
        ResidentList::create([
            'residentID' => '105',
            'houseID' => '37',
            'houseNumber'=>'5',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);   
        ResidentList::create([
            'residentID' => '106',
            'houseID' => '37',
            'houseNumber'=>'5',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);   
        //38 107 108 109
        ResidentList::create([
            'residentID' => '107',
            'houseID' => '38',
            'houseNumber'=>'5',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);   
        ResidentList::create([
            'residentID' => '108',
            'houseID' => '38',
            'houseNumber'=>'5',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);   
        ResidentList::create([
            'residentID' => '109',
            'houseID' => '38',
            'houseNumber'=>'5',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);   
        
        
        //39 110 111 112
        ResidentList::create([
            'residentID'=>'110',
            'houseID'=>'39',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'111',
            'houseID'=>'39',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'112',
            'houseID'=>'39',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //40 113 114 115
        ResidentList::create([
            'residentID'=>'113',
            'houseID'=>'40',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'114',
            'houseID'=>'40',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'115',
            'houseID'=>'40',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //41 116 117 118
        ResidentList::create([
            'residentID'=>'116',
            'houseID'=>'41',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'117',
            'houseID'=>'41',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'118',
            'houseID'=>'41',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //42 119 120 121 122
        ResidentList::create([
            'residentID'=>'119',
            'houseID'=>'42',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'120',
            'houseID'=>'42',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'121',
            'houseID'=>'42',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'122',
            'houseID'=>'42',
            'houseNumber'=>'2',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //43 123 124 125 126
        ResidentList::create([
            'residentID'=>'123',
            'houseID'=>'43',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'124',
            'houseID'=>'43',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'125',
            'houseID'=>'43',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'126',
            'houseID'=>'43',
            'houseNumber'=>'2',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //44 127 128 129 130
        ResidentList::create([
            'residentID'=>'127',
            'houseID'=>'44',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'128',
            'houseID'=>'44',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'129',
            'houseID'=>'44',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'130',
            'houseID'=>'44',
            'houseNumber'=>'2',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //45 131 132 133 134 135
        ResidentList::create([
            'residentID'=>'131',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'132',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'133',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'134',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'135',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //45 131 132 133 134 135
        ResidentList::create([
            'residentID'=>'131',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'132',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'133',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'134',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'135',
            'houseID'=>'45',
            'houseNumber'=>'3',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);


         //46 136 137 138 139 140
        ResidentList::create([
            'residentID'=>'136',
            'houseID'=>'46',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'137',
            'houseID'=>'46',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'138',
            'houseID'=>'46',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'139',
            'houseID'=>'46',
            'houseNumber'=>'3',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'140',
            'houseID'=>'46',
            'houseNumber'=>'3',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //47 141 142 143 144 145
        ResidentList::create([
            'residentID'=>'141',
            'houseID'=>'47',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'142',
            'houseID'=>'47',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'143',
            'houseID'=>'47',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'144',
            'houseID'=>'47',
            'houseNumber'=>'3',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'145',
            'houseID'=>'47',
            'houseNumber'=>'3',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //48 146 147 148 149
        ResidentList::create([
            'residentID'=>'146',
            'houseID'=>'48',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'147',
            'houseID'=>'48',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'148',
            'houseID'=>'48',
            'houseNumber'=>'4',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'149',
            'houseID'=>'48',
            'houseNumber'=>'4',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //49 150 151 152 153
        ResidentList::create([
            'residentID'=>'150',
            'houseID'=>'49',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'151',
            'houseID'=>'49',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'152',
            'houseID'=>'49',
            'houseNumber'=>'4',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'153',
            'houseID'=>'49',
            'houseNumber'=>'4',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //50 154 155 156 157
        ResidentList::create([
            'residentID'=>'154',
            'houseID'=>'50',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'155',
            'houseID'=>'50',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'156',
            'houseID'=>'50',
            'houseNumber'=>'4',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'157',
            'houseID'=>'50',
            'houseNumber'=>'4',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);


        //51 158 159 160 161 162
        ResidentList::create([
            'residentID'=>'158',
            'houseID'=>'51',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'159',
            'houseID'=>'51',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'160',
            'houseID'=>'51',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'161',
            'houseID'=>'51',
            'houseNumber'=>'1',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'162',
            'houseID'=>'51',
            'houseNumber'=>'1',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //52 163 164 165 166 167
        ResidentList::create([
            'residentID'=>'163',
            'houseID'=>'52',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'164',
            'houseID'=>'52',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'165',
            'houseID'=>'52',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'166',
            'houseID'=>'52',
            'houseNumber'=>'1',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'167',
            'houseID'=>'52',
            'houseNumber'=>'1',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);


        //53 168 169 170 171 172
        ResidentList::create([
            'residentID'=>'168',
            'houseID'=>'53',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'169',
            'houseID'=>'53',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'170',
            'houseID'=>'53',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'171',
            'houseID'=>'53',
            'houseNumber'=>'1',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'172',
            'houseID'=>'53',
            'houseNumber'=>'1',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //54 173 174 175 
        ResidentList::create([
            'residentID'=>'173',
            'houseID'=>'54',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'174',
            'houseID'=>'54',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'175',
            'houseID'=>'54',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //55 176 177 178
        ResidentList::create([
            'residentID'=>'176',
            'houseID'=>'55',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'177',
            'houseID'=>'55',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'178',
            'houseID'=>'55',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //56 179 180 181
        ResidentList::create([
            'residentID'=>'179',
            'houseID'=>'56',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'179',
            'houseID'=>'56',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'179',
            'houseID'=>'56',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //57 182 183
        ResidentList::create([
            'residentID'=>'182',
            'houseID'=>'57',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'183',
            'houseID'=>'57',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //58 184 185
        ResidentList::create([
            'residentID'=>'184',
            'houseID'=>'58',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'185',
            'houseID'=>'58',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //59 186 187
        ResidentList::create([
            'residentID'=>'186',
            'houseID'=>'59',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'187',
            'houseID'=>'59',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //60 188
        ResidentList::create([
            'residentID'=>'188',
            'houseID'=>'60',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //61 189
        ResidentList::create([
            'residentID'=>'189',
            'houseID'=>'61',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //62 190
        ResidentList::create([
            'residentID'=>'190',
            'houseID'=>'62',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //63 191 192 193
        ResidentList::create([
            'residentID'=>'191',
            'houseID'=>'63',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'192',
            'houseID'=>'63',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'193',
            'houseID'=>'63',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //64 194 195 196
        ResidentList::create([
            'residentID'=>'194',
            'houseID'=>'64',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'195',
            'houseID'=>'64',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'196',
            'houseID'=>'64',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //65 197 198 199
        ResidentList::create([
            'residentID'=>'197',
            'houseID'=>'65',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'198',
            'houseID'=>'65',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'199',
            'houseID'=>'65',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //66 200 201 202
        ResidentList::create([
            'residentID'=>'200',
            'houseID'=>'66',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'201',
            'houseID'=>'66',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'202',
            'houseID'=>'66',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //67 203 204 205
        ResidentList::create([
            'residentID'=>'203',
            'houseID'=>'67',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'204',
            'houseID'=>'67',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'205',
            'houseID'=>'67',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //68 206 207 208
        ResidentList::create([
            'residentID'=>'206',
            'houseID'=>'68',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'207',
            'houseID'=>'68',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'208',
            'houseID'=>'68',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //69 209 210 211
        ResidentList::create([
            'residentID'=>'209',
            'houseID'=>'69',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'210',
            'houseID'=>'69',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'211',
            'houseID'=>'69',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //70 212 213 214
        ResidentList::create([
            'residentID'=>'212',
            'houseID'=>'70',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'213',
            'houseID'=>'70',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'214',
            'houseID'=>'71',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //71 215 216 217
        ResidentList::create([
            'residentID'=>'215',
            'houseID'=>'71',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'216',
            'houseID'=>'71',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'217',
            'houseID'=>'71',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        
        //72 218 219 220
        ResidentList::create([
            'residentID'=>'218',
            'houseID'=>'72',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'219',
            'houseID'=>'72',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'220',
            'houseID'=>'72',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //73 221 222 223
        ResidentList::create([
            'residentID'=>'221',
            'houseID'=>'73',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'222',
            'houseID'=>'73',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'223',
            'houseID'=>'73',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //74 224 225 226
        ResidentList::create([
            'residentID'=>'224',
            'houseID'=>'74',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'225',
            'houseID'=>'74',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'226',
            'houseID'=>'74',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);



        //75 227 228 229 230
        ResidentList::create([
            'residentID'=>'227',
            'houseID'=>'75',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'228',
            'houseID'=>'75',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'229',
            'houseID'=>'75',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'230',
            'houseID'=>'75',
            'houseNumber'=>'1',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //76 231 232 233 234
        ResidentList::create([
            'residentID'=>'231',
            'houseID'=>'76',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'232',
            'houseID'=>'76',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'233',
            'houseID'=>'76',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'234',
            'houseID'=>'76',
            'houseNumber'=>'1',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //77 235 236 237 238
        ResidentList::create([
            'residentID'=>'235',
            'houseID'=>'77',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'236',
            'houseID'=>'77',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'237',
            'houseID'=>'77',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'238',
            'houseID'=>'77',
            'houseNumber'=>'1',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);


        //78 249 250
        ResidentList::create([
            'residentID'=>'249',
            'houseID'=>'78',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'250',
            'houseID'=>'78',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //79 251 252
        ResidentList::create([
            'residentID'=>'251',
            'houseID'=>'79',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'252',
            'houseID'=>'79',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //80 253 254
        ResidentList::create([
            'residentID'=>'253',
            'houseID'=>'80',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'254',
            'houseID'=>'80',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //81 255 256
        ResidentList::create([
            'residentID'=>'255',
            'houseID'=>'81',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'256',
            'houseID'=>'81',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //82 257 258
        ResidentList::create([
            'residentID'=>'257',
            'houseID'=>'82',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'258',
            'houseID'=>'82',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //83 259 260
        ResidentList::create([
            'residentID'=>'259',
            'houseID'=>'83',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'260',
            'houseID'=>'83',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //84 261 262
        ResidentList::create([
            'residentID'=>'261',
            'houseID'=>'84',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'260',
            'houseID'=>'84',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //85 263 264
        ResidentList::create([
            'residentID'=>'263',
            'houseID'=>'85',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'264',
            'houseID'=>'85',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //86 265 266
        ResidentList::create([
            'residentID'=>'265',
            'houseID'=>'86',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'266',
            'houseID'=>'86',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //10

        //87 267 268 269
        ResidentList::create([
            'residentID'=>'267',
            'houseID'=>'87',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'268',
            'houseID'=>'87',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'269',
            'houseID'=>'87',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //88 270 271 272
        ResidentList::create([
            'residentID'=>'270',
            'houseID'=>'88',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'271',
            'houseID'=>'88',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'272',
            'houseID'=>'88',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //89 273 274 275
        ResidentList::create([
            'residentID'=>'273',
            'houseID'=>'89',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'274',
            'houseID'=>'89',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'275',
            'houseID'=>'89',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //90 276 277
        ResidentList::create([
            'residentID'=>'276',
            'houseID'=>'90',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'277',
            'houseID'=>'90',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //91 278 279
        ResidentList::create([
            'residentID'=>'278',
            'houseID'=>'91',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'279',
            'houseID'=>'91',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //92 280 281
        ResidentList::create([
            'residentID'=>'280',
            'houseID'=>'92',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'281',
            'houseID'=>'92',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //11

        //93 282 283
        ResidentList::create([
            'residentID'=>'282',
            'houseID'=>'93',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'283',
            'houseID'=>'93',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //94 284 285
        ResidentList::create([
            'residentID'=>'284',
            'houseID'=>'94',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'285',
            'houseID'=>'94',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //95 286 287
        ResidentList::create([
            'residentID'=>'286',
            'houseID'=>'95',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'286',
            'houseID'=>'95',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //96 288 289 290
        ResidentList::create([
            'residentID'=>'288',
            'houseID'=>'96',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'289',
            'houseID'=>'96',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'290',
            'houseID'=>'96',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //97 291 292 293
        ResidentList::create([
            'residentID'=>'291',
            'houseID'=>'97',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'292',
            'houseID'=>'97',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'293',
            'houseID'=>'97',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //98 294 295 296
        ResidentList::create([
            'residentID'=>'294',
            'houseID'=>'98',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'295',
            'houseID'=>'98',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'296',
            'houseID'=>'98',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //99 297 298 299
        ResidentList::create([
            'residentID'=>'297',
            'houseID'=>'99',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'298',
            'houseID'=>'99',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'299',
            'houseID'=>'99',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //100 300 301 302
        ResidentList::create([
            'residentID'=>'300',
            'houseID'=>'100',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'301',
            'houseID'=>'100',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'302',
            'houseID'=>'100',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //101 303 304 305
        ResidentList::create([
            'residentID'=>'303',
            'houseID'=>'101',
            'houseNumber'=>'3',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'303',
            'houseID'=>'101',
            'houseNumber'=>'3',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'303',
            'houseID'=>'101',
            'houseNumber'=>'3',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //102 306 307 308 309
        ResidentList::create([
            'residentID'=>'306',
            'houseID'=>'102',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'307',
            'houseID'=>'102',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'308',
            'houseID'=>'102',
            'houseNumber'=>'4',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'309',
            'houseID'=>'102',
            'houseNumber'=>'4',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //103 310 311 312 313
        ResidentList::create([
            'residentID'=>'310',
            'houseID'=>'103',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'311',
            'houseID'=>'103',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'312',
            'houseID'=>'103',
            'houseNumber'=>'4',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'313',
            'houseID'=>'103',
            'houseNumber'=>'4',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //104 314 315 316 317
        ResidentList::create([
            'residentID'=>'314',
            'houseID'=>'104',
            'houseNumber'=>'4',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'314',
            'houseID'=>'104',
            'houseNumber'=>'4',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'314',
            'houseID'=>'104',
            'houseNumber'=>'4',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'314',
            'houseID'=>'104',
            'houseNumber'=>'4',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //105 318 319
        ResidentList::create([
            'residentID'=>'318',
            'houseID'=>'105',
            'houseNumber'=>'5A',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'319',
            'houseID'=>'105',
            'houseNumber'=>'5A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //106 320 321
        ResidentList::create([
            'residentID'=>'320',
            'houseID'=>'106',
            'houseNumber'=>'5A',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'321',
            'houseID'=>'106',
            'houseNumber'=>'5A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //107 322 323
        ResidentList::create([
            'residentID'=>'322',
            'houseID'=>'107',
            'houseNumber'=>'5A',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'323',
            'houseID'=>'107',
            'houseNumber'=>'5A',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //108 324 325 326 327
        ResidentList::create([
            'residentID'=>'324',
            'houseID'=>'108',
            'houseNumber'=>'5B',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'325',
            'houseID'=>'108',
            'houseNumber'=>'5B',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'326',
            'houseID'=>'108',
            'houseNumber'=>'5B',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'327',
            'houseID'=>'108',
            'houseNumber'=>'5B',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //109 328 329 330 331
        ResidentList::create([
            'residentID'=>'328',
            'houseID'=>'109',
            'houseNumber'=>'5B',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'329',
            'houseID'=>'109',
            'houseNumber'=>'5B',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'330',
            'houseID'=>'109',
            'houseNumber'=>'5B',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'331',
            'houseID'=>'109',
            'houseNumber'=>'5B',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //110 332 333 334 335
        ResidentList::create([
            'residentID'=>'332',
            'houseID'=>'110',
            'houseNumber'=>'5B',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'333',
            'houseID'=>'110',
            'houseNumber'=>'5B',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'334',
            'houseID'=>'110',
            'houseNumber'=>'5B',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'335',
            'houseID'=>'110',
            'houseNumber'=>'5B',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //111 336 337 338
        ResidentList::create([
            'residentID'=>'336',
            'houseID'=>'111',
            'houseNumber'=>'6',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'337',
            'houseID'=>'111',
            'houseNumber'=>'6',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'338',
            'houseID'=>'111',
            'houseNumber'=>'6',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //112 339 340 341
        ResidentList::create([
            'residentID'=>'337',
            'houseID'=>'112',
            'houseNumber'=>'6',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'338',
            'houseID'=>'112',
            'houseNumber'=>'6',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'339',
            'houseID'=>'112',
            'houseNumber'=>'6',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //113 342 343 344
        ResidentList::create([
            'residentID'=>'340',
            'houseID'=>'113',
            'houseNumber'=>'6',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'341',
            'houseID'=>'113',
            'houseNumber'=>'6',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'342',
            'houseID'=>'113',
            'houseNumber'=>'6',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //12
        
        //114 345 346 347
        ResidentList::create([
            'residentID'=>'345',
            'houseID'=>'114',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'346',
            'houseID'=>'114',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'347',
            'houseID'=>'114',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //115 348 349 350
        ResidentList::create([
            'residentID'=>'348',
            'houseID'=>'115',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'349',
            'houseID'=>'115',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'350',
            'houseID'=>'115',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //116 351 352 353 
        ResidentList::create([
            'residentID'=>'351',
            'houseID'=>'116',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'352',
            'houseID'=>'116',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'353',
            'houseID'=>'116',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        
        //117 354 355
        ResidentList::create([
            'residentID'=>'354',
            'houseID'=>'117',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'355',
            'houseID'=>'117',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //118 356 357
        ResidentList::create([
            'residentID'=>'356',
            'houseID'=>'118',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'357',
            'houseID'=>'118',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //119 358 359
        ResidentList::create([
            'residentID'=>'358',
            'houseID'=>'119',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'359',
            'houseID'=>'119',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //13 
        
        //120 360 361 362
        ResidentList::create([
            'residentID'=>'360',
            'houseID'=>'120',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'361',
            'houseID'=>'120',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'362',
            'houseID'=>'120',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //121 363 364 365
        ResidentList::create([
            'residentID'=>'363',
            'houseID'=>'121',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'364',
            'houseID'=>'121',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'365',
            'houseID'=>'121',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //122 366 367 368
        ResidentList::create([
            'residentID'=>'366',
            'houseID'=>'122',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'367',
            'houseID'=>'122',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'368',
            'houseID'=>'122',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //123 369 370 371 372 373 374
        ResidentList::create([
            'residentID'=>'369',
            'houseID'=>'123',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'370',
            'houseID'=>'123',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'371',
            'houseID'=>'123',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'372',
            'houseID'=>'123',
            'houseNumber'=>'2',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'373',
            'houseID'=>'123',
            'houseNumber'=>'2',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'374',
            'houseID'=>'123',
            'houseNumber'=>'2',
            'memberNumber'=>6,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //124 375 376 377 378 379 380
        ResidentList::create([
            'residentID'=>'375',
            'houseID'=>'124',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'376',
            'houseID'=>'124',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'377',
            'houseID'=>'124',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'378',
            'houseID'=>'124',
            'houseNumber'=>'2',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'379',
            'houseID'=>'124',
            'houseNumber'=>'2',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'380',
            'houseID'=>'124',
            'houseNumber'=>'2',
            'memberNumber'=>6,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //125 381 382 383 384 385 386
        ResidentList::create([
            'residentID'=>'381',
            'houseID'=>'125',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'382',
            'houseID'=>'125',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'383',
            'houseID'=>'125',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'384',
            'houseID'=>'125',
            'houseNumber'=>'2',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'385',
            'houseID'=>'125',
            'houseNumber'=>'2',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'386',
            'houseID'=>'125',
            'houseNumber'=>'2',
            'memberNumber'=>6,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //14
        
        //126 387 388 389
        ResidentList::create([
            'residentID'=>'387',
            'houseID'=>'126',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'388',
            'houseID'=>'126',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'389',
            'houseID'=>'126',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //127 390 391 392
        ResidentList::create([
            'residentID'=>'390',
            'houseID'=>'127',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'391',
            'houseID'=>'127',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'392',
            'houseID'=>'127',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //128 393 394 395
        ResidentList::create([
            'residentID'=>'393',
            'houseID'=>'128',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'394',
            'houseID'=>'128',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'395',
            'houseID'=>'128',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

        //129 396 397 398
        ResidentList::create([
            'residentID'=>'396',
            'houseID'=>'129',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'397',
            'houseID'=>'129',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'398',
            'houseID'=>'129',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //130 399 400 401
        ResidentList::create([
            'residentID'=>'399',
            'houseID'=>'130',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'400',
            'houseID'=>'130',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'401',
            'houseID'=>'130',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        //131 402 403 404
        ResidentList::create([
            'residentID'=>'402',
            'houseID'=>'131',
            'houseNumber'=>'2',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'403',
            'houseID'=>'131',
            'houseNumber'=>'2',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'404',
            'houseID'=>'131',
            'houseNumber'=>'2',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);

/*      ResidentList::create([
            'residentID'=>'X',
            'houseID'=>'X',
            'houseNumber'=>'1',
            'memberNumber'=>1,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'X',
            'houseID'=>'X',
            'houseNumber'=>'1',
            'memberNumber'=>2,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'X',
            'houseID'=>'X',
            'houseNumber'=>'1',
            'memberNumber'=>3,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'X',
            'houseID'=>'X',
            'houseNumber'=>'1',
            'memberNumber'=>4,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'X',
            'houseID'=>'X',
            'houseNumber'=>'1',
            'memberNumber'=>5,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
        ResidentList::create([
            'residentID'=>'X',
            'houseID'=>'X',
            'houseNumber'=>'1',
            'memberNumber'=>6,
            'createdBy'=>2,
            'revisedBy'=>2,
        ]);
*/
    }
}
